name: 'reMarkable ctest'
description: 'GitHub Action to post result of ctest runs as comments'
author: 'reMarkable'
inputs:
  logfile:
    required: true
    description: 'The ctest log'
    default: 'build/ctest.log'
runs:
  using: 'node12'
  main: 'dist/index.js'
