name: 'reMarkable ctest'
description: 'GitHub Action to post result of ctest runs as comments'
author: 'reMarkable'
inputs:
  logfile:
    required: true
    description: 'The ctest log'
    default: 'build/ctest.log'
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  platform:
    description: Description of where the tests were run
    default: Unknown OS (please set platform)
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
